#Used source to help develop this file: https://makefiletutorial.com/

CC = $(CROSS_COMPILE)gcc
#writer: writer.c
#	cc writer.c -o writer

#default target
all: writer

writer: writer.o

clean:
	rm -f writer writer.o
